insert into ods_codeforces__submission (
    codeforces_submission_id,
    contest_id,
    creation_time_seconds,
    relative_time_seconds,
    problem_contest_id,
    problem_index,
    problem_name,
    problem_type,
    problem_points,
    problem_rating,
    problem_tags_json,
    author_handle,
    author_participant_type,
    author_json,
    programming_language,
    verdict,
    testset,
    passed_test_count,
    time_consumed_millis,
    memory_consumed_bytes,
    batch_id,
    fetched_at,
    raw_payload,
    payload_hash
) values (
    :codeforcesSubmissionId,
    :contestId,
    :creationTimeSeconds,
    :relativeTimeSeconds,
    :problemContestId,
    :problemIndex,
    :problemName,
    :problemType,
    :problemPoints,
    :problemRating,
    :problemTagsJson,
    :authorHandle,
    :authorParticipantType,
    :authorJson,
    :programmingLanguage,
    :verdict,
    :testset,
    :passedTestCount,
    :timeConsumedMillis,
    :memoryConsumedBytes,
    :batchId,
    :fetchedAt,
    :rawPayload,
    :payloadHash
)
on duplicate key update
    contest_id = values(contest_id),
    creation_time_seconds = values(creation_time_seconds),
    relative_time_seconds = values(relative_time_seconds),
    problem_contest_id = values(problem_contest_id),
    problem_index = values(problem_index),
    problem_name = values(problem_name),
    problem_type = values(problem_type),
    problem_points = values(problem_points),
    problem_rating = values(problem_rating),
    problem_tags_json = values(problem_tags_json),
    author_handle = values(author_handle),
    author_participant_type = values(author_participant_type),
    author_json = values(author_json),
    programming_language = values(programming_language),
    verdict = values(verdict),
    testset = values(testset),
    passed_test_count = values(passed_test_count),
    time_consumed_millis = values(time_consumed_millis),
    memory_consumed_bytes = values(memory_consumed_bytes),
    batch_id = values(batch_id),
    fetched_at = values(fetched_at),
    raw_payload = values(raw_payload),
    payload_hash = values(payload_hash),
    updated_at = current_timestamp(6);
